name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        project: ["avl-bag", "first_lab"]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: ocaml/setup-ocaml@v2
    
    - name: Install dependencies
      run: opam install dune alcotest -y
    
    - name: Build ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        dune build
    
    - name: Test ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        dune runtest
